### ISSUE TITLE
Storyboard Personal Information Section

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#101]
As an eApp designer I want to derive a design concept that illustrates the initial eApp questionnaire form styles and flow so that the programmers can build a prototype that represents the design concept, and users can test the prototype to validate, or challenge, the design decisions.

Acceptance Criteria
- Aggregate style decisions and wireframes into a single Storyboard representing an initial design concept 
- Review the storyboard/comp with the Product Owner 
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
[e-app-sections-1-4.pdf](https://github.com/truetandem/e-QIP-prototype/files/649860/e-app-sections-1-4.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-sections-1-4-v2-1](https://cloud.githubusercontent.com/assets/19935974/21158346/f4cd4586-c14a-11e6-9400-afe83ea3e524.jpg)
![e-qip-comp-sections-1-4-v2-2](https://cloud.githubusercontent.com/assets/19935974/21158347/f4ceba92-c14a-11e6-9825-59469fe449e5.jpg)
![e-qip-comp-sections-1-4-v2-3](https://cloud.githubusercontent.com/assets/19935974/21158350/f4d02daa-c14a-11e6-8458-abe74b3ef256.jpg)
![e-qip-comp-sections-1-4-v2-4](https://cloud.githubusercontent.com/assets/19935974/21158349/f4cf9c6e-c14a-11e6-892c-5c7e5cb976d6.jpg)
![e-qip-comp-sections-1-4-v2-5](https://cloud.githubusercontent.com/assets/19935974/21158351/f4d413c0-c14a-11e6-824a-c756c7863514.jpg)
![e-qip-comp-sections-1-4-v2-6](https://cloud.githubusercontent.com/assets/19935974/21158348/f4cf338c-c14a-11e6-91e5-dd3ee915bc9e.jpg)
![e-qip-comp-sections-1-4-v2-7](https://cloud.githubusercontent.com/assets/19935974/21158352/f4d4a966-c14a-11e6-8551-e95b4bb90c12.jpg)
![e-qip-comp-sections-1-4-v2-8](https://cloud.githubusercontent.com/assets/19935974/21158353/f4d52b20-c14a-11e6-99be-962cf0900692.jpg)
![e-qip-comp-sections-1-4-v2-9](https://cloud.githubusercontent.com/assets/19935974/21158354/f4d5f0dc-c14a-11e6-81af-8a90d1729c23.jpg)
![e-qip-comp-sections-1-4-v2-10](https://cloud.githubusercontent.com/assets/19935974/21158356/f4d7035a-c14a-11e6-93c0-e174163a0d59.jpg)
![e-qip-comp-sections-1-4-v2-11](https://cloud.githubusercontent.com/assets/19935974/21158355/f4d6dda8-c14a-11e6-8525-26922401d2ba.jpg)
![Uploading e-QIP-comp-sections-1-4-V2-12.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-13.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-14.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-15.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-16.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-17.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-18.jpg…]()
![Uploading e-QIP-comp-sections-1-4-V2-19.jpg…]()

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-sections-1-4-v2-1](https://cloud.githubusercontent.com/assets/19935974/21158426/35bbed36-c14b-11e6-8146-d305bdca2100.jpg)
![e-qip-comp-sections-1-4-v2-2](https://cloud.githubusercontent.com/assets/19935974/21158430/35c522fc-c14b-11e6-8604-9eb3e66acaee.jpg)
![e-qip-comp-sections-1-4-v2-3](https://cloud.githubusercontent.com/assets/19935974/21158428/35c44fe4-c14b-11e6-8221-0a867eb23c76.jpg)
![e-qip-comp-sections-1-4-v2-4](https://cloud.githubusercontent.com/assets/19935974/21158432/35c9d950-c14b-11e6-8cdc-391964fd81c6.jpg)
![e-qip-comp-sections-1-4-v2-5](https://cloud.githubusercontent.com/assets/19935974/21158429/35c5179e-c14b-11e6-83c8-c1fa8398fa36.jpg)
![e-qip-comp-sections-1-4-v2-6](https://cloud.githubusercontent.com/assets/19935974/21158431/35c6f00a-c14b-11e6-9a9a-cf3eccf70d67.jpg)
![e-qip-comp-sections-1-4-v2-7](https://cloud.githubusercontent.com/assets/19935974/21158427/35c37d26-c14b-11e6-8649-2d98dad6083f.jpg)
![e-qip-comp-sections-1-4-v2-8](https://cloud.githubusercontent.com/assets/19935974/21158433/35cc45c8-c14b-11e6-9c8b-9386ff86c45c.jpg)
![e-qip-comp-sections-1-4-v2-9](https://cloud.githubusercontent.com/assets/19935974/21158434/35cdec34-c14b-11e6-85cd-5b65acb1e79b.jpg)
![e-qip-comp-sections-1-4-v2-10](https://cloud.githubusercontent.com/assets/19935974/21158435/35ce7a0a-c14b-11e6-872f-15102a67fb9e.jpg)
![e-qip-comp-sections-1-4-v2-11](https://cloud.githubusercontent.com/assets/19935974/21158436/35ce7bb8-c14b-11e6-9cee-93be974581d0.jpg)
![e-qip-comp-sections-1-4-v2-12](https://cloud.githubusercontent.com/assets/19935974/21158439/35d43440-c14b-11e6-9c97-f77980e2d1c4.jpg)
![e-qip-comp-sections-1-4-v2-13](https://cloud.githubusercontent.com/assets/19935974/21158437/35d06a18-c14b-11e6-975b-b2170b05a741.jpg)
![e-qip-comp-sections-1-4-v2-14](https://cloud.githubusercontent.com/assets/19935974/21158438/35d3e2ba-c14b-11e6-9890-ed19294da8aa.jpg)
![e-qip-comp-sections-1-4-v2-15](https://cloud.githubusercontent.com/assets/19935974/21158443/35d90696-c14b-11e6-9bc2-2377edb21c75.jpg)
![e-qip-comp-sections-1-4-v2-16](https://cloud.githubusercontent.com/assets/19935974/21158440/35d56694-c14b-11e6-9ce1-521fbb00fb63.jpg)
![e-qip-comp-sections-1-4-v2-17](https://cloud.githubusercontent.com/assets/19935974/21158442/35d6daba-c14b-11e6-8af5-306ba954b287.jpg)
![e-qip-comp-sections-1-4-v2-18](https://cloud.githubusercontent.com/assets/19935974/21158441/35d6a0d6-c14b-11e6-9aae-ed879f16f48f.jpg)
![e-qip-comp-sections-1-4-v2-19](https://cloud.githubusercontent.com/assets/19935974/21158444/35db2584-c14b-11e6-8520-dfff4eccbd75.jpg)

**Comment by jehlers** [comment]
Hey @Jay-Neighbours-I72, it's looking good! I'm going to list my feedback here so you have it all in one place. Let me know if you have any questions. :)

#### Header
- “Identifying Information” - Is that the current name of this group in the form? It feels very... vague and stiff. Could we try something a little more plain and inviting like “Biographical information” or something else? Thoughts?
- What happens when I click eApp? Logout feels a little weird there because there are no other generalized links. It may work perfectly there, but I think it depends on what eApp does.
- Along the same lines, “eApp” means absolutely nothing. It is fine as an internal name, but I do not think it helps the user identify where they are or feel official. Along those lines, it might be good to look into the use of a seal or something that would make this page feel a part of something bigger and “official.” 
- I also don’t see the SF-86 form number anywhere. Maybe that is a good candidate for the eApp spot? Then the user at least knows what form they are filling out.

#### Nav
- Is the darker green "/29” a compliant ratio on top of the medium green? This is my favorite tool to check because you can put your whole color palette in: https://accessibility.oit.ncsu.edu/tools/color-contrast/ and then save the link for the future. 
- I did not notice the sub sections until 5-6 pages in. They a lot like the higher level sections as opposed to something coming out from the section above them.
- I like what you are doing with the numbers on the left, but they feel very disconnected to the label. I don’t think the line between the ON and error ones helps that disconnect either. Maybe if they lived more inside the strokes with the labels? Even if you have to make the labels bigger, I don't think that would hurt. But we will see once all 29 sections are in. :) 

#### General
- For some labels you are using Title Case, and some you are using Sentence case. I think we should be consistent throughout. My preference is Sentence case because it is friendlier (especially when we get down to long questions) and easier to read. But whichever way works for you, works for me so long as we are consistent.
- I'm a little confused by the overall interaction of the page. So, to clarify, I can’t click next until I’ve filled out all the information on a page, but can I skip around in the nav? Is that correct or am I missing something?

#### Form fields
- Check boxes should have checks in them. I like what you are trying to do with the filled in box for “Initial only” but because we will have radio buttons and check boxes I think its really important to indicate to the user which interaction they are doing. 
- This is a larger question. Since we were talking about people without first names as well… should we allow for no first name?
- Should it go first, middle, last name? That would follow the way someone would say their name.
- Place of birth - The text under the title feels like it has a lot of leading and space. It is also very similar in visual weight as the label. I almost missed the “state or country” label because they blend together a bit.
- SSN is missing the (check) icon when everything is validated. 


#### Help text box
- When the green stroke is around a validated box, the help box (?) doesn’t feel like it fits. Its a little weird too next to the darker stroke of a normal input field.
- I’m a little concerned that the box pushes down the estimated check box. That field is very very closely related to the text fields and I worry someone who needs it will miss it if the help box is expanded. 
- Where did you get the text for the Date of Birth help box? The first two lines seem helpful… the note seems redundant. 
- Now that I’m seeing real copy there, I’m not sure the check under the (i) makes sense. I see what you are trying to do, but since its only at the first “bullet” point, and not the second something feels wrong. I also think a check may be the wrong connotation for help text.

#### Error messages
- I’m not sure we need the left bar. There’s already 3 indicators of an error without that bar. 
- I love the individualized input error message for the SSN. Not sure the green and red is working together. It may be easier to just call out the red one. 
- Also if we are going to talk about something missing in an field with more than one inputs, to account for color blindness our error message should be more specific. Something like “the last field in your social security number should have 4 digits.”
- Also “check this number to ensure it is right” feels out of place in the SSN error. Seems like something that should be moved out and is always around? Maybe?

#### Review page
- I’m not sure the striping is working because you have the other gray left nav. It may be worth using more white space and a light stroke to separate sections on this page. That way we have less grays that not all computers will be able to pick up the nuances between.

**Comment by Jay-Neighbours-I72** [comment]
Version 3 starts here:

![e-qip-comp-sections-1-4-v3-1](https://cloud.githubusercontent.com/assets/19935974/21353177/f1578bb2-c692-11e6-9175-ced411f4c7e2.jpg)
![e-qip-comp-sections-1-4-v3-2](https://cloud.githubusercontent.com/assets/19935974/21353179/f159846c-c692-11e6-8028-d76cbc18b9b1.jpg)
![e-qip-comp-sections-1-4-v3-3](https://cloud.githubusercontent.com/assets/19935974/21353178/f1585740-c692-11e6-96a2-20495b03e1ba.jpg)
![e-qip-comp-sections-1-4-v3-4](https://cloud.githubusercontent.com/assets/19935974/21353181/f159eb28-c692-11e6-8059-fc179b0d9256.jpg)
![e-qip-comp-sections-1-4-v3-5](https://cloud.githubusercontent.com/assets/19935974/21353180/f159de08-c692-11e6-88ee-e2d7f1f28822.jpg)
![e-qip-comp-sections-1-4-v3-6](https://cloud.githubusercontent.com/assets/19935974/21353182/f15adbe6-c692-11e6-96dc-429057997c80.jpg)
![e-qip-comp-sections-1-4-v3-7](https://cloud.githubusercontent.com/assets/19935974/21353184/f15f7b74-c692-11e6-91b9-2ebe6d1c5561.jpg)
![e-qip-comp-sections-1-4-v3-8](https://cloud.githubusercontent.com/assets/19935974/21353183/f15ec602-c692-11e6-8a8b-e72b6bcef8d8.jpg)
![e-qip-comp-sections-1-4-v3-9](https://cloud.githubusercontent.com/assets/19935974/21353185/f15fb4d6-c692-11e6-86c1-7c70728474a2.jpg)
![e-qip-comp-sections-1-4-v3-10](https://cloud.githubusercontent.com/assets/19935974/21353187/f1601188-c692-11e6-9d92-1a19a50678c6.jpg)
![e-qip-comp-sections-1-4-v3-11](https://cloud.githubusercontent.com/assets/19935974/21353186/f15fcb42-c692-11e6-9d52-7b5606663472.jpg)
![e-qip-comp-sections-1-4-v3-12](https://cloud.githubusercontent.com/assets/19935974/21353188/f1623364-c692-11e6-8dcf-9aa2031d7c6e.jpg)
![e-qip-comp-sections-1-4-v3-13](https://cloud.githubusercontent.com/assets/19935974/21353189/f164f680-c692-11e6-9e8f-35698f382fad.jpg)
![e-qip-comp-sections-1-4-v3-14](https://cloud.githubusercontent.com/assets/19935974/21353190/f1662cbc-c692-11e6-9acb-da283d17c338.jpg)
![e-qip-comp-sections-1-4-v3-15](https://cloud.githubusercontent.com/assets/19935974/21353191/f1669616-c692-11e6-9385-9191a8b657c8.jpg)
![e-qip-comp-sections-1-4-v3-16](https://cloud.githubusercontent.com/assets/19935974/21353193/f166d0cc-c692-11e6-86ce-5677f3098d84.jpg)
![e-qip-comp-sections-1-4-v3-17](https://cloud.githubusercontent.com/assets/19935974/21353192/f166af7a-c692-11e6-902b-0b6c874966f2.jpg)
![e-qip-comp-sections-1-4-v3-18](https://cloud.githubusercontent.com/assets/19935974/21353194/f16817ca-c692-11e6-846c-1aba28ac773a.jpg)
![e-qip-comp-sections-1-4-v3-19](https://cloud.githubusercontent.com/assets/19935974/21353198/f16f1192-c692-11e6-9111-3a50af4862dc.jpg)
![e-qip-comp-sections-1-4-v3-20](https://cloud.githubusercontent.com/assets/19935974/21353195/f16d443e-c692-11e6-9509-a7ae67d5e31f.jpg)
![e-qip-comp-sections-1-4-v3-21](https://cloud.githubusercontent.com/assets/19935974/21353197/f16da816-c692-11e6-8cdb-fb84e136f3aa.jpg)
![e-qip-comp-sections-1-4-v3-22](https://cloud.githubusercontent.com/assets/19935974/21353196/f16d84b2-c692-11e6-8f60-61dd3e894d75.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-sections-1-4-V3.pdf](https://github.com/truetandem/e-QIP-prototype/files/664147/e-QIP-comp-sections-1-4-V3.pdf)

**Comment by Jay-Neighbours-I72** [comment]
Version 4 starts here:

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-sections-1-4-v4-1](https://cloud.githubusercontent.com/assets/19935974/21367372/ebde91f6-c6cb-11e6-8cfb-7693ac8265e5.jpg)
![e-qip-comp-sections-1-4-v4-2](https://cloud.githubusercontent.com/assets/19935974/21367378/ebe8b5aa-c6cb-11e6-81aa-7b9e4b577fcf.jpg)
![e-qip-comp-sections-1-4-v4-3](https://cloud.githubusercontent.com/assets/19935974/21367374/ebe752d2-c6cb-11e6-9817-39e9b6a41022.jpg)
![e-qip-comp-sections-1-4-v4-4](https://cloud.githubusercontent.com/assets/19935974/21367377/ebe83008-c6cb-11e6-9819-bb28d3e625c8.jpg)
![e-qip-comp-sections-1-4-v4-5](https://cloud.githubusercontent.com/assets/19935974/21367373/ebe6de88-c6cb-11e6-83d6-049aba8b1e98.jpg)
![e-qip-comp-sections-1-4-v4-6](https://cloud.githubusercontent.com/assets/19935974/21367375/ebe78c48-c6cb-11e6-97be-808400057321.jpg)
![e-qip-comp-sections-1-4-v4-7](https://cloud.githubusercontent.com/assets/19935974/21367376/ebe78324-c6cb-11e6-86ec-a43f654bcb4a.jpg)
![e-qip-comp-sections-1-4-v4-8](https://cloud.githubusercontent.com/assets/19935974/21367380/ebee8b10-c6cb-11e6-80b6-abf65fc857eb.jpg)
![e-qip-comp-sections-1-4-v4-9](https://cloud.githubusercontent.com/assets/19935974/21367382/ebefed0c-c6cb-11e6-971f-27a3396bd46a.jpg)
![e-qip-comp-sections-1-4-v4-10](https://cloud.githubusercontent.com/assets/19935974/21367379/ebee87c8-c6cb-11e6-9602-3f315fa62572.jpg)
![e-qip-comp-sections-1-4-v4-11](https://cloud.githubusercontent.com/assets/19935974/21367381/ebef0054-c6cb-11e6-9e1d-140274f3a8dc.jpg)
![e-qip-comp-sections-1-4-v4-12](https://cloud.githubusercontent.com/assets/19935974/21367383/ebf12708-c6cb-11e6-9100-f53d9005bde4.jpg)
![e-qip-comp-sections-1-4-v4-13](https://cloud.githubusercontent.com/assets/19935974/21367384/ebf2004c-c6cb-11e6-9156-713220a66c26.jpg)
![e-qip-comp-sections-1-4-v4-14](https://cloud.githubusercontent.com/assets/19935974/21367385/ebf5f6ac-c6cb-11e6-9b17-f8d235d1d611.jpg)
![e-qip-comp-sections-1-4-v4-15](https://cloud.githubusercontent.com/assets/19935974/21367389/ebf80abe-c6cb-11e6-9315-ca22df018a37.jpg)
![e-qip-comp-sections-1-4-v4-16](https://cloud.githubusercontent.com/assets/19935974/21367386/ebf67fd2-c6cb-11e6-98af-07c0afd2671e.jpg)
![e-qip-comp-sections-1-4-v4-17](https://cloud.githubusercontent.com/assets/19935974/21367388/ebf8041a-c6cb-11e6-8f8c-328164b741f1.jpg)
![e-qip-comp-sections-1-4-v4-18](https://cloud.githubusercontent.com/assets/19935974/21367387/ebf7f90c-c6cb-11e6-94d9-2479760a2111.jpg)
![e-qip-comp-sections-1-4-v4-19](https://cloud.githubusercontent.com/assets/19935974/21367390/ebf96fa8-c6cb-11e6-8370-6e28444cca6c.jpg)
![e-qip-comp-sections-1-4-v4-20](https://cloud.githubusercontent.com/assets/19935974/21367392/ebfed772-c6cb-11e6-8622-21f67a42f3e1.jpg)
![e-qip-comp-sections-1-4-v4-21](https://cloud.githubusercontent.com/assets/19935974/21367391/ebfec822-c6cb-11e6-86b7-1821d2fd2ab4.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-sections-1-4-V4.pdf](https://github.com/truetandem/e-QIP-prototype/files/664726/e-QIP-comp-sections-1-4-V4.pdf)
