### ISSUE TITLE
Slow build times on TravisCI

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1022]
The build times seem to be running around 20 to 30 minutes. Need to investigate what may be causing thes if anything at all. Local tests take a minute or so.

**Comment by floresj** [comment]
In the travis ci logs, I'm seeing versions of our dependencies that differ from what's in our `package.json`. For instance, react-dom@15.5.4  shows up but we have react-dom@15.3.2 in our `package.json`. I wonder if that's causing those deprecated statements to show up since it's pulling dependencies that are newer. I'm sure it doesn't help that all those deprecated statements are being printed for every test being ran.

**Comment by bmallred** [comment]
Yeah that would definitely be an issue!

**Comment by bmallred** [comment]
3f35ce4 is attempting to leverage the caching capabilities in **TravisCI**

**Comment by bmallred** [comment]
Receiving much better build times as of https://github.com/truetandem/e-QIP-prototype/pull/1046/commits/ff646366ff32aac00f53c58ace8b0ffae471a4cd. Went from >= 45m down to about an average of 9m.

Leaving this open for monitoring purposes.

cc: @adelevie @floresj

**Comment by adelevie** [comment]
Great work!
