### ISSUE TITLE
Emotional health - headline margins 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1037]
- [x] Margins are a bit off on this section - may need to revisit site wide?

![screen shot 2017-04-25 at 10 46 05 am](https://cloud.githubusercontent.com/assets/19935974/25391510/66a2bb84-29a4-11e7-8390-cfd7f450198b.png)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 These are using `h2` headline styles whereas most of our other Fields have been using `h3`. Do you think in this case I should switch to using `h3` instead of `h2`?

Here's a screen depicting actual size relative to another component (Diagnoses subsection).
![selection_047](https://cloud.githubusercontent.com/assets/5938731/25445481/8a267aae-2a7c-11e7-92fe-71e731bdb42b.png)

**Comment by floresj** [comment]
Related issue which appears to be hitting on `h2`'s. #1033

**Comment by Jay-Neighbours-I72** [comment]
H2 makes sense here, just need to iron out the margins. I'd say for now give them more top margin and we can tighten in that other issue

**Comment by floresj** [comment]
Updated agency
![screen shot 2017-04-26 at 12 17 52 pm](https://cloud.githubusercontent.com/assets/5938731/25452424/6f9497ea-2a7a-11e7-94c3-abc86dc4f053.png)
