### ISSUE TITLE
ApplicantAddress server-side validation

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#115]
- [ ] Street 1: length x
 - [ ] Street 2: length x; Optional
 - [ ] Apt: length x; optional
 - [ ] City: length x: ensure zip/state/city match up
 - [ ] State: length 2; ensure zip/state/city match up
 - [ ] Zip: length 5; ensure zip/state/city match up
 - [ ] If P.O. Box is entered, provide a comment as to why (e.g. rural address, etc...)
 - [ ] Full address validation against an external API

The external validation may be a 1-to-1 or a "fastest" round-trip scenario.

**Comment by floresj** [comment]
USPS Web service documentation can be found https://www.usps.com/business/web-tools-apis/address-information-api.htm

## Summary
The USPS web api has three capabilities. These include:

1. [Address Standardization Web Tool](https://www.usps.com/business/web-tools-apis/address-information-api.htm#_Toc410982981)
   - Corrects errors in street addresses, including abbreviations and missing information, and supplies ZIP Codes and ZIP Codes + 4
     - For instance, if zipcode is not provided in request, it will be provided in response
     - Updates `Court` to `CT`
     - For misspellings, appropriately resolves address and returns correct spelling (this depends on the degree to which the address information was misspelled)
2. [ZIP Code Lookup Web Tool](https://www.usps.com/business/web-tools-apis/address-information-api.htm#_Toc410982986)
    - Returns the ZIP Code and ZIP Code + 4 corresponding to the given address, city, and state 
3. [City/State Lookup Web Tool](https://www.usps.com/business/web-tools-apis/address-information-api.htm#_Toc410982991)
    -  Returns the city and state corresponding to the given ZIP Code


## Request Structure
Not all fields are required. The `USERID` attribute on the root tag is the id associated to the registration
```xml
<AddressValidateRequest USERID="XXXXX">
  <Address ID="0">  
    <FirmName />   
    <Address1 />   
    <Address2></Address2>   
    <City></City>   
    <State></State>   
    <Zip5></Zip5>   
    <Zip4></Zip4> 
  </Address>      
</AddressValidateRequest>
```

## Response Structure
```xml
<AddressValidateResponse>
  <Address ID="0">
    <Address2></Address2>
    <City></City>
    <State></State>
    <Zip5></Zip5>
    <Zip4></Zip4>
    <DeliveryPoint></DeliveryPoint>
    <CarrierRoute></CarrierRoute>
  </Address>
</AddressValidateResponse>
```

**Comment by floresj** [comment]
## eApp Usage

The basic idea is to take user inputted address information and compare it against the USPS. When determining the validity of an address, the following conditions are possible

### 1. Exact address hit
This is a scenario where the user has inputted the exact address information. This excludes case-sensitivity. For instance, if the user has inputted the following

```xml
<AddressValidateRequest>
    <Address>
        <Address2>123 Some Rd</Address2>
        <City>Arlington</City>
        <State>VA</State>
        <Zip5>22202</Zip5>
        <Zip4></Zip4>
    </Address>
</AddressValidateRequest>
```

and the response comes back as

```xml
<AddressValidateRequest>
    <Address>
        <Address2>123 SOME RD</Address2>
        <City>ARLINGTON</City>
        <State>VA</State>
        <Zip5>22202</Zip5>
        <Zip4></Zip4>
    </Address>
</AddressValidateRequest>
```

This response is an exact match since all fields match.

### 2. Partial Match
This is a response where address information was validated however there may be some minor discrepancies between what was inputted versus what was returned. This can occur for these cases
- User enters the full name for a road type like `Road`, `Street`. USPS returns RD and ST. 
  - 123 Some Road -> 123 Some RD
  - 123 Some Street -> 123 Some ST
- User misspells a city or street name that is then corrected by the validation
  - Arlingtonn -> Arlington

### 3. Partial Match with Default Address
This may be prevalent with apartment based addresses. This occurs if a user enters an appropriate address to an apartment complex but fails to include an apartment number or includes an incorrect apartment number.

The error message returned by USPS is
`Default address: The address you entered was found but more information is needed (such as an apartment, suite, or box number) to match to a specific address.`

For instance, if a user enters

```
300 10th RD S
Arlington, VA 22202
```

and this is an apartment complex, the USPS geocoder may return the Default Address message indicating that the base address is correct however no specific number was specified

However, if a user enters

```
300 10th RD S APT 100
Arlington, VA 22202
```

If apt 100 is a valid number, this would resolve correctly.

### 4. No address found
This is a response when USPS cannot resolve any address information based on the inputs.
