### ISSUE TITLE
Police record - offenses and additional offenses

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1213]
For both the Offenses and Additional offenses sections:

- [x] If user answers yes to 1 of the yes/no questions no change

- [x] If user answers yes to 2 or more of the yes/no questions add this line above the accordion:
"You answered yes to multiple questions. Add details for each individual offense below."

1 yes =
<img width="1327" alt="screen shot 2017-05-10 at 4 22 16 pm" src="https://cloud.githubusercontent.com/assets/19935974/25919789/c965419c-359d-11e7-9f19-d802b3577463.png">

2+ yes =
<img width="1370" alt="screen shot 2017-05-10 at 4 27 16 pm" src="https://cloud.githubusercontent.com/assets/19935974/25919794/cf95f4b2-359d-11e7-9180-ff721f076e5f.png">

**Comment by lauraponce** [comment]
Is it possible to decrease the width of this text area so that more of it falls onto the second line avoiding the orphan word? It fits onto one line above 1728px, but for smaller widths, the word "below" drops to line two. @floresj @bmallred 

![screen shot 2017-05-16 at 11 47 51 am](https://cloud.githubusercontent.com/assets/21222704/26115274/8407f9e8-3a2d-11e7-910b-585e7fb116e7.png)

**Comment by billy22g** [comment]
Bump above question for @bmallred @floresj and @Jay-Neighbours-I72

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Think we should have the `You answered yes ...below` text line up with `Summary of offenses` and `Offense 1` text? This would reduce the width as well.

**Comment by Jay-Neighbours-I72** [comment]
@floresj @billy22g @lauraponce 

I think this line can go away completely because it was added specifically for the multiple yes/no buttons.

Since we are going back to a list and single yes/no I don't think it is needed anymore.

**Comment by lauraponce** [comment]
Good point, @Jay-Neighbours-I72 ! Agreed.

**Comment by billy22g** [comment]
Good point, and yep. cc: @floresj

**Comment by floresj** [comment]
@billy22g  @Jay-Neighbours-I72 @lauraponce With the buttons removed, we get this:
![selection_158](https://user-images.githubusercontent.com/5938731/26879136-f34fcd6c-4b5d-11e7-86f1-34ddd9bcf4e9.png)

However, what should we do about the help content that we initially had on two of the previous `yes/no` buttons? Should we just include both help text information inside of the single `yes/no` branch now?

These were the two options that had help content:
![selection_156](https://user-images.githubusercontent.com/5938731/26879175-1c488dc6-4b5e-11e7-9b27-46807efab79d.png)

![selection_157](https://user-images.githubusercontent.com/5938731/26879174-1c46ab6e-4b5e-11e7-91ee-d5b2ad9d7f1d.png)

**Comment by billy22g** [comment]
That, or potentially including them as part of that question in parens due
to possible confusion.

**Comment by Jay-Neighbours-I72** [comment]
I think we will need to include them back with the questions, as paragraph text.
@floresj

**Comment by floresj** [comment]
How's this

![selection_166](https://user-images.githubusercontent.com/5938731/26980290-b1df2c30-4cff-11e7-97b0-61aad0dc436c.png)

**Comment by billy22g** [comment]
I'm going to add this to the "Needs answer" category, because this is just absurdly confusing ("other than those offenses already listed" vs "include even if previously listed on this form".
 
<img width="713" alt="screen shot 2017-06-18 at 1 34 18 pm" src="https://user-images.githubusercontent.com/5091167/27263637-ef13e4f6-542a-11e7-92c2-a1cb9166fbfd.png">

**Comment by billy22g** [comment]
Other than that, LGTM.
