### ISSUE TITLE
Relatives -DOB Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1264]
DOB is required if :

_- [ ] Mother is selected as relative type_
or
_- [ ] Father is selected as relative type_
or
_- [ ] Child is selected as relative type_
N/A

Mother specific Validation:

- [x] Format: MM/DD/YYYY
- [x] Date must be greater than or equal to NOW-200. Date must be less than or equal to NOW

Father specific Validation:
- [x] Format: MM/DD/YYYY
- [x] Date must be greater than or equal to NOW-200. Date must be less than or equal to NOW

Child specific Validation:
- [x] Format: MM/DD/YYYY
- [x] Date must be greater than DOB and less than NOW

<img width="1201" alt="screen shot 2017-05-22 at 10 40 06 am" src="https://cloud.githubusercontent.com/assets/19935974/26314150/0ac8dfa4-3edb-11e7-8ccc-8193daba32f8.png">

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @bmallred @floresj and I chatted about this one a bit and thought it was strange we only want a DOB for those 3 relative types (Child, father, mother)

Does that seem ok to you?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Nope, the content guide clearly asked for DOB from all of them. I would expect this is the first of many issues you see with this validation matrix. It's why I'm so insistent that we do not just use it because it's in there, but rather gut check everything to make sure it makes sense.

<img width="653" alt="screen shot 2017-05-22 at 5 05 43 pm" src="https://cloud.githubusercontent.com/assets/5091167/26328482/3971fa30-3f11-11e7-9fe0-183ae8e3cb9b.png">

For the others, it seems like we can use the NOW - 200 for the greater than date, even though that's going to be very loose in many cases (e.g. siblings). Make sense?

**Comment by Jay-Neighbours-I72** [comment]
Sounds good, that is clear direction and should reduce the number of these validation GH issues.

**Comment by Jay-Neighbours-I72** [comment]
Looks like the wrong message is being used for Relative DOB:
![screen shot 2018-01-04 at 11 26 49 am](https://user-images.githubusercontent.com/19935974/34573461-3eddc524-f142-11e7-976e-d5d2d683a511.png)

**Comment by bmallred** [comment]
Looks like the calculations are correct, but the messages need to be tailored.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Looks like this is still pulling from the user's DOB instead of the relatives DOB

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is still in progress. The dates are pulling from the appropriate places but the error message is not changing to note the difference is all. I'll move this in to review/QA when ready for another look :smile:

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this one will be ready for another look. Updating `dev` now.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
