### ISSUE TITLE
Storyboard Save Progress

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1306]
Design a way for users to see their progress is being saved.

**Comment by Jay-Neighbours-I72** [comment]
Option 1:
Text link next to the auto save, this would give users that extra bit of assurance their progress was being saved
![e-app-save-button-option-1](https://cloud.githubusercontent.com/assets/19935974/26456540/58ad3690-413b-11e7-8842-2d232918b78b.jpg)


-
Option 2:
Floating save icon that sticks to vertical center or bottom of browser window so user can save at any point without scrolling down.
![e-app-save-button-option-2](https://cloud.githubusercontent.com/assets/19935974/26456541/58af592a-413b-11e7-8ad6-f697f5215f0c.jpg)


-
Regroup with @lauraponce when she is back next week.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 maybe a combination of both?

I personally like **Option 1** but I know the system is saving it. **Option 2** gives that extra bit of comfort for most users.

**Comment by Jay-Neighbours-I72** [comment]
Both is definitely an option.

Might be overkill or users might love it.

**Comment by billy22g** [comment]
I *think* option 1 still is likely to have similar issues with people not seeing it until they're all the way down at the bottom, but I could be wrong.

**Comment by lauraponce** [comment]
I agree with Billy that option 1 might still have the same issue with it being missed in the first place (though once they saw it, it would solve the peace of mind issue for them if they can click a physical save button). 

I am leaning towards the second option for the fact that it's more present. What if, in addition to the floating action button, the text saying autosaved 30 seconds ago was up there too with it instead of down at the bottom?

One other thought that I think came up in the last round of usability testing was having the section title (or the subsection title/main question) lock in place at the top and follow them through the section – if that's still something worth considering then that could also be a good place for the autosave (this is how Google Docs displays the last saved messaging). Thoughts on that @Jay-Neighbours-I72 ? If it's out of scope of this particular issue, feel free to ignore!

**Comment by Jay-Neighbours-I72** [comment]
I think we could squeeze the autosaved text under the floating button, I'll comp something up.

I think the sticky header and sticky accordion headers would be really helpful.

The header pieces is in the icebox too: https://github.com/truetandem/e-QIP-prototype/issues/1197

**Comment by Jay-Neighbours-I72** [comment]
It fits, we will have to explore it on smaller screens and I think the text would need to be tweaked slightly to make sense on physical saves. Ex: Saved: Just now

<img width="2043" alt="screen shot 2017-06-01 at 11 16 56 am" src="https://cloud.githubusercontent.com/assets/19935974/26686763/f757a020-46bb-11e7-9a57-bfa7c7e24125.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I like that. For mobile how do you picture this? Something like bottom-right corner?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred My gut is to have it at the bottom under the back/next buttons.

I'm hesitant to have anything fixed on mobile because it steals valuable real estate and clutters it a bit.

**Comment by bmallred** [comment]
Sounds good :+1:

**Comment by billy22g** [comment]
LGTM
