### ISSUE TITLE
Storyboard subnav complete/error style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1308]
Option 1:
Small, subtle green and red circles, Conveys message without being busy.
![e-app-subnav-icons-option-1](https://cloud.githubusercontent.com/assets/19935974/26458351/f61085ea-4140-11e7-96ba-acc207716a72.jpg)

-
Option 2:
Full size check and exclamation point icons. May be a bit busy.
![e-app-subnav-icons-option-2](https://cloud.githubusercontent.com/assets/19935974/26458355/f9287b66-4140-11e7-8ca6-49754f5d214c.jpg)

Regroup with @lauraponce when she is back.

**Comment by billy22g** [comment]
cc: @lauraponce I'll leave this for you. I like the subtler green dots I think. The checks seem like too much going on.

**Comment by lauraponce** [comment]
I like the subtler version of the dots too. I think this will be really useful for people! It doesn't seem like we need to draw attention to that area (which is what I think the second example would do); it's more of just a status indicator for those sections. I'd be curious to see what folks think it means in usability testing to see if they draw the connection from not finishing the section to the red dot or if they think it's something they entered that was wrong. 

@Jay-Neighbours-I72 what are your thoughts on making this left nav sticky so that when they scroll, it follows them down? I think this came up in our debrief after UT the other week, but I don't remember where we landed.

**Comment by Jay-Neighbours-I72** [comment]
Yeah i love the idea of the sticky nav @lauraponce. We will just need to make sure we think through specific functionality. 

It is in the icebox here:
https://github.com/truetandem/e-QIP-prototype/issues/1198

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @floresj Let's go ahead with the small dots.

**Comment by bmallred** [comment]
## Preview
![nav-small-icons](https://cloud.githubusercontent.com/assets/697855/26700131/3d942c38-46ea-11e7-8490-ab299948abac.png)

**Comment by billy22g** [comment]
LGTM
