### ISSUE TITLE
Accordions - should be closed when you leave and return

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1321]
cc: @Jay-Neighbours-I72 @lauraponce 

My interpretation is that if you leave a section with accordions and then come back, that they should be closed. Currently, e.g. Your History, if you fill out a couple, leave, then come back, all the accordions are open which is very confusing.

**Comment by floresj** [comment]
Issue #1256 is being worked on to address this issue.

**Comment by billy22g** [comment]
I'm not sure this is done. If there's a single accordion item, it still loads as open when you come back. Is that desired @Jay-Neighbours-I72? My interpretation was that they would all be closed, whether you have 1 or more, upon coming back.

**Comment by lauraponce** [comment]
@billy22g that's the intended behavior of the accordion – it's supposed to be closed if there are multiple items so that people can go to the one they need, but if there is just one, it's supposed to be open when they come back since that's the only item they would need to update. @Jay-Neighbours-I72 please correct me if I'm wrong though, I remember this coming up a few weeks ago.

**Comment by billy22g** [comment]
Got it, thanks! To me that’s a bit confusing but totally seems like a personal preference thing that we could test the hypothesis with users in usability testing and find out whether they expect that or not.

________________________________

**Comment by bmallred** [comment]
@billy22g @lauraponce @Jay-Neighbours-I72 it should be noted that if there is only a single item in an accordion and they navigate to the review screen then it should be **collapsed** as well.

**Comment by billy22g** [comment]
That's helpful, thanks @bmallred.
