### ISSUE TITLE
Military History - SSS help text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1342]
The SSS number help text (Can't remember your number...) should be the help text connected to that question. It will still load open but clicking the help icon will close and re-open it.

Add "Close info block" link

Remove duplicate help message (opened when clicking on the help icon)

<img width="1340" alt="screen shot 2017-05-31 at 10 05 49 am" src="https://cloud.githubusercontent.com/assets/19935974/26635862/0c292baa-45e9-11e7-86c9-9b7e1d09fae9.png">

Duplicate help
<img width="1474" alt="duplicate help" src="https://cloud.githubusercontent.com/assets/19935974/26635863/0c32f43c-45e9-11e7-9bb3-46a25f5597db.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 In the initial design this "help" message was specifically designed to be displayed by itself. Should this change?

## Design comp
![e-app-comp-military-history-05](https://cloud.githubusercontent.com/assets/697855/26636887/fd9fd61c-45eb-11e7-824a-149f79122110.jpg)

**Comment by Jay-Neighbours-I72** [comment]
No, that functionality is the same.

It will automatically be open when the user lands here. They should still be able to close it though.

Would an easier solution be to remove the help on that question?

That would solve my duplicate help text issue.

@bmallred

**Comment by bmallred** [comment]
Definitely would be easier. Currently the help text is opened via events which we don't have a tie-in to force this. That isn't saying we can't do it, but just wasn't built that way currently.

**Comment by Jay-Neighbours-I72** [comment]
Got it, let's remove that help text then.

**Comment by Jay-Neighbours-I72** [comment]
Removed help text. all good

**Comment by billy22g** [comment]
@bmallred Can you decrease the spacing a bit between the input and the help box, as in the design comp?

**Comment by bmallred** [comment]
Because this isn't a normal field usage had to tweak some of the styling to get this to match the drawing. I noticed that on the web application it is always visible, but in the design comp it is only visible when **Yes** is selected. Curious which way to go on that.

cc: @billy22g @Jay-Neighbours-I72 

## Neutral

![no-margin-neutral](https://cloud.githubusercontent.com/assets/697855/26813454/51b18d22-4a4c-11e7-9385-68d41991932c.png)

## No

![no-margin-no](https://cloud.githubusercontent.com/assets/697855/26813451/4e296a44-4a4c-11e7-85b8-5f6f609a5ccb.png)

## Yes

![no-margin-yes](https://cloud.githubusercontent.com/assets/697855/26813448/4a90b5d6-4a4c-11e7-8e88-9ce1cf828f75.png)

**Comment by billy22g** [comment]
My gut is the design comp is correct. That the help box should only be visible once you've selected yes.

**Comment by Jay-Neighbours-I72** [comment]
Agreed, it is directly related to that "Yes"

**Comment by bmallred** [comment]
Cool, it's in the PR :smile:

**Comment by billy22g** [comment]
Looks great!
