### ISSUE TITLE
People who know you well - accordion scroll

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1351]
- [ ] Accordion is not scrolling users up far enough when adding a new item

Current scroll:
<img width="2081" alt="screen shot 2017-05-31 at 1 48 08 pm" src="https://cloud.githubusercontent.com/assets/19935974/26645980/f36795e2-4607-11e7-9ae7-5affe6a3d54e.png">

Desired:
<img width="2080" alt="screen shot 2017-05-31 at 1 48 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/26645983/f4fe21c8-4607-11e7-9331-e4b8aa55962d.png">

**Comment by bmallred** [comment]
Related to #1249? If so PR #1292 will hopefully clear that up.

**Comment by Jay-Neighbours-I72** [comment]
These will be a bit different @bmallred 

The accordions that have a progress bar above them will have a larger space at the top so the first new item a user will see the progress bar

**Comment by bmallred** [comment]
Gotcha, similar to what we applied in **Your History**

**Comment by Jay-Neighbours-I72** [comment]
Yeah, doesn't look like those are scrolling up enough either though.

<img width="2081" alt="screen shot 2017-05-31 at 2 15 53 pm" src="https://cloud.githubusercontent.com/assets/19935974/26646961/b64c9fa0-460b-11e7-883e-32a5bfdb9a78.png">

**Comment by billy22g** [comment]
I'm still seeing it not scroll up so that the progress bar is visible in the employment section of Your History. Same as Jay's last screenshot above.

That said, @Jay-Neighbours-I72, after the second item, it's probably unreasonable to scroll up that far because the context should be on the item they're now entering after they've clicked "Add another." Is it only at the first "Add another" that they should see that progress bar?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g 

Exactly, the goal is to have the user see the progress bar after the first "Add another" so they understand it.

That way they can scroll back up to it whenever they want and their focus will be on the new item added.

**Comment by billy22g** [comment]
@bmallred The above make sense?

**Comment by Jay-Neighbours-I72** [comment]
Looks good
