### ISSUE TITLE
Selective Service - conditional suggestion

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1370]
@bmallred and I were talking through an idea for this question.

Pull the user's DOB and Gender from section 1.
If user is not a male born after 12/31/1959 they don't see the Selective Service question at all.

@billy22g @lauraponce Thoughts on this? Especially if we would be allowed to do it or not.

 
<img width="1443" alt="screen shot 2017-06-05 at 11 12 27 am" src="https://cloud.githubusercontent.com/assets/19935974/26790044/517fdfe6-49e0-11e7-929b-709918bb3bb1.png">

**Comment by lauraponce** [comment]
I love the idea of using the data they have already entered to answer this question. I'm really not sure about if this is something we are "allowed" to do. I would lean towards this being okay since it's a black and white question, the paper form would have to ask just because there is no other way to do it, but it would be removing a whole question. @billy22g – thoughts?

Maybe if we are decided on removing it, there could be some language saying "Because you are a male born after December 31, 1959, there are some additional questions for you to answer." at the top and possibly more details for them with something in the help text letting them know we are using the info they provided in section 1? @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
@lauraponce That makes a lot of sense and I like it, the wording should be tweaked to reflect the change.

**Comment by Jay-Neighbours-I72** [comment]
Per review discussion we can hide the Selective Service question with the age requirement only.

**Comment by billy22g** [comment]
LGTM!
