### ISSUE TITLE
Military history - US Military green dot not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1374]
Completed US Military section is not showing green dot.

<img width="2071" alt="screen shot 2017-06-05 at 2 49 53 pm" src="https://cloud.githubusercontent.com/assets/19935974/26798400/421cda86-49fe-11e7-888d-a54fd40bd170.png">

**Comment by billy22g** [comment]
Since I closed the other one, I'll just leave this here. If you select "No" on U.S. military, disciplinary procedures is still the next section, even though it doesn't show up in the subsection list. This is really important.

<img width="1272" alt="screen shot 2017-06-06 at 3 30 04 pm" src="https://user-images.githubusercontent.com/5091167/26852948-4261f506-4acd-11e7-8c58-110c95bd8931.png">

**Comment by bmallred** [comment]
This is what I see:
![untitled](https://user-images.githubusercontent.com/697855/26853069-8acb1ee2-4ade-11e7-84bb-a0b7aada35d1.png)

**Comment by billy22g** [comment]
Right, your screenshot is of a different page (foreign military). Assuming
the user selected "No" for U.S. military, the disciplinary procedures
section should not be after U.S. military. See the back button on your
screenshot and the next button on mine.

**Comment by billy22g** [comment]
Oh, nevermind, got the email but looks like you deleted that comment. :)

**Comment by billy22g** [comment]
LGTM
