### ISSUE TITLE
Left navigation - collapse subsections when not in use

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1377]
Following the same pattern of the rest of the left navigation let's collapse all subsections that are not in use.

<img width="484" alt="screen shot 2017-06-05 at 4 22 56 pm" src="https://cloud.githubusercontent.com/assets/19935974/26801668/93cfa374-4a0b-11e7-8def-0cd84b4badc5.png">

**Comment by bmallred** [comment]
Reference #1390 for additional styling which came about at a later review.

**Comment by bmallred** [comment]
## Larger resolution

![larger-screen-arrows](https://user-images.githubusercontent.com/697855/27545274-6d200cf2-5a5d-11e7-86d5-5a13ff6395c3.png)

## Smaller resolution

![smaller-screen-arrows](https://user-images.githubusercontent.com/697855/27545273-6d1d0fde-5a5d-11e7-96a6-4f3e8f9c7ca7.png)

cc: @lauraponce @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
I like it!

May have some tiny tweaks once I play with it in browser

**Comment by bmallred** [comment]
Sounds good :)

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @bmallred I'm going to close this one and call it complete because it satisfies what you asked for. However, the upward (collapse) icon signifies to me that a user should be able to collapse an open section or subsection. That's currently not possible, so imo we should either 1. remove that icon because it's misleading, or 2. make it work as expected.

**Comment by bmallred** [comment]
@billy22g that is a good point. This will probably resolve itself once we implement the additional navigation changes in #1500!
