### ISSUE TITLE
People who know you well - years covered being incorrectly calculated?

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1416]
1. Added a person who had known me for 14 years.
2. form says only 6 of 7 years covered.
![screen shot 2017-06-13 at 2 46 22 pm](https://user-images.githubusercontent.com/26907482/27098966-48a71034-5047-11e7-82e5-1f1840395b45.png)

**Comment by bmallred** [comment]
So the year counter is just for the last seven years. May 5th, 2017 (with an allowed buffer of 30 days) does not meet the full 7 year requirement and that is why it is stating 6 out of 7.

What we did in the **Your history** section was the text was "Years covered" instead of "Years" to help mitigate confusion. Thoughts?

cc: @Jay-Neighbours-I72 @gabesnyder @floresj @lauraponce @billy22g @pjsumm

**Comment by bmallred** [comment]
Something like this...

![counter-with-padding](https://user-images.githubusercontent.com/697855/27146611-e8c2e0c8-5107-11e7-9ab7-c4e910ae3c82.png)

**Comment by billy22g** [comment]
LGTM
