### ISSUE TITLE
Substance use - order of questions creates unhelpful treatment nickname

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1460]
Normally the accordion nickname is the drug in question. In this case, the treatment accordion title is the entity that ordered treatment, not the drug.

https://eqip-prototype-staging.fr.cloud.gov/form/substance/drugs/ordered

Maybe not a bug? but a departure from what we do elsewhere on the form.

![screen shot 2017-06-19 at 2 11 13 pm](https://user-images.githubusercontent.com/26907482/27300713-9a4c2ada-54fe-11e7-8e67-e2961679e48c.png)

**Comment by Jay-Neighbours-I72** [comment]
This is a tricky one since there isn't much info the user is inputing.

Using the button text as the headline might not work like Gabe pointed out because users can select multiple buttons and it would be hard to differentiate between accordion items.

Let's use the explanation field instead, it will be truncated but will be unique to each accordion item.

Sound good @gabesnyder @bmallred @floresj ?

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Do we want to keep the date info too?

**Comment by colinpmacarthur** [comment]
Looks like the accordion title is indeed displaying the explanation field, which makes sense to me! I think this one is ready for done, @billy22g.

**Comment by billy22g** [comment]
Thanks @colinpmacarthur! Agreed!
