### ISSUE TITLE
Citizenship - Foreign activities subsection

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1476]
Let's break foreign passport question out into its own subsection.

So the full organization would be:

**Citizenship**
        Citizenship Status
        Dual/Multiple Citizenship
        Foreign Passports

**Comment by floresj** [comment]
@Jay-Neighbours-I72  The `Foreign Passports` portion of the `Dual/Multiple Citizenship` subsection was originally a branch collection (repeating Yes/No). I'm switching it over to a normal collection since it will be its own subsection. Now, within this `Foreign Passports`, there's a nested collection. I'm going to switch that to a branch collection to avoid nested collections. Is that ok? #CollectionInception.

**Comment by colinpmacarthur** [comment]
Makes sense to me and is functioning as described. cc: @billy22g

**Comment by billy22g** [comment]
LGTM!
