### ISSUE TITLE
Storyboard Adding Attachments

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1572]
As an eApp designer I want to storyboard how a user will attach items to their SF-86 form, and how those items will be viewed, listed, removed and removed so that the eApp developers can prototype the design 

Acceptance:
- Use #1521 for behavior
- Design follows existing standards
- Design is approved by 18f PMO
- Design is approved by Product Owner

**Comment by Jay-Neighbours-I72** [comment]
V1 of adding attachments:

- First 2 jpgs show how a user will encounter the Add attachment block in the form
- The other jpgs give a full walkthrough of the process
- Instruction/detail text has been put into the help
- Goal is to follow the same functionality and style as we've been using throughout the form
- Direct fax and other - text is placeholder since we didn't have content for this page

![e-app-comp-attachments-in-form-1](https://user-images.githubusercontent.com/19935974/28720375-feff8590-737a-11e7-8e34-ad38b13e08dd.jpg)
![e-app-comp-attachments-in-form-2](https://user-images.githubusercontent.com/19935974/28720374-fefd1062-737a-11e7-9221-c9856754fb00.jpg)
![e-app-comp-attachment-1](https://user-images.githubusercontent.com/19935974/28720381-037dd6bc-737b-11e7-8c28-b636bedbfd44.jpg)
![e-app-comp-attachment-2](https://user-images.githubusercontent.com/19935974/28720382-038207aa-737b-11e7-9580-0104663c4b0c.jpg)
![e-app-comp-attachment-3](https://user-images.githubusercontent.com/19935974/28720384-038568d2-737b-11e7-984e-20ed09029020.jpg)
![e-app-comp-attachment-4](https://user-images.githubusercontent.com/19935974/28720383-03844cfe-737b-11e7-90e5-611e80b8e29a.jpg)
![e-app-comp-attachment-5](https://user-images.githubusercontent.com/19935974/28720386-0388416a-737b-11e7-8f19-8c1ba4cbf7c9.jpg)
![e-app-comp-attachment-6](https://user-images.githubusercontent.com/19935974/28720387-0388dddc-737b-11e7-9518-da7a719b3c9a.jpg)
![e-app-comp-attachment-7](https://user-images.githubusercontent.com/19935974/28720385-03866a98-737b-11e7-898e-0e2e59493eb1.jpg)

PDF:
[e-APP-comp-attachment-v1.pdf](https://github.com/truetandem/e-QIP-prototype/files/1183228/e-APP-comp-attachment-v1.pdf)

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Didn't Sheldon say we wouldn't be supporting fax?

**Comment by Jay-Neighbours-I72** [comment]
It seemed up in the air to me based on the email response and Sheldon.

Luckily that style is flexible enough to evolve... if Fax is out that option goes away. if both fax and other are out the full choice block goes away and just the upload portion is there.

**Comment by colinpmacarthur** [comment]
Let's double check during today's standup?

**Comment by billy22g** [comment]
LGTM. As discussed in standup, we'll present tomorrow with caveat that implementation will likely change based on Sheldon and Drew's review.

**Comment by billy22g** [comment]
Discussion in sprint review:

1. Should we only accept pdf, or also support jpg, png, others?
2. Question: can we accept multiple types but just convert everything to one file type to send to NBIB? (need to figure out how to support the current e-QIP/PIPS/OPIS flow)
3. Need to allow for direct upload *and* another type.
4. How does this work on mobile?
