### ISSUE TITLE
Relationships - cohabitants - no way to provide multiple other names

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1587]
no way to add more than one additional ‘other names’ used by cohabitant. 
instructions say to add dates for time period that ‘each name’ was used.
![screen shot 2017-07-18 at 4 04 55 pm](https://user-images.githubusercontent.com/26907482/28337232-f773d6e6-6bd2-11e7-9831-b19b38b95bdc.png)

**Comment by floresj** [comment]
In the content guide (page 13 right before the start of Section 18) is where this question lives.
![selection_334](https://user-images.githubusercontent.com/5938731/28381315-6cd0ff80-6c88-11e7-873f-6894ec0b62bb.png)

I see that it mentions `Other names` but it doesn't specify that multiple names can specified. This is probably something we should ask and then track since it deviates from the normal form.

cc: @Jay-Neighbours-I72 @bmallred

**Comment by Jay-Neighbours-I72** [comment]
I'll track it.

I think we can treat it like other sections:

Add another name used?
Yes button \ No button

yes loads name fields and another "add another"

@floresj let me know when it is up so i can take a screenshot for the tracking doc

**Comment by floresj** [comment]
@Jay-Neighbours-I72 I like your style. This will also resolve #1602. I'll let ya know. Gracias!

**Comment by billy22g** [comment]
LGTM
