### ISSUE TITLE
Handle required field errors within Review Screen

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#1599]
As a user, I want to see errors for required fields that have not been completed within the section review screen.

Sections with review screens:

- [x] Identification
- [x] Financial record
- [x] Your History
- [x] Relationships
- [x] Citizenship
- [x] Military history
- [x] Foreign activities
- [x] Substance use
- [x] Investigative and criminal history
- [x] Psychological and emotional health

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Any ideas on what the required error state would look like for questions that use radio/checkbox options? For instance, take `Eye color` and `Select your sex` from `Your identifying information`, 

![selection_335](https://user-images.githubusercontent.com/5938731/28382564-8998c482-6c8c-11e7-8faf-6d3a3e8825de.png)

Would just having the red box with error text under the question suffice? Or would we need some sort of vicious red border somewhere like we do with textfields?

cc: @bmallred

**Comment by Jay-Neighbours-I72** [comment]
Good question... This is for when the full question isn't answered right?

**Comment by floresj** [comment]
Yessssssir.

**Comment by Jay-Neighbours-I72** [comment]
Let's pull from existing error styles like this:

<img width="1145" alt="screen shot 2017-07-20 at 9 58 01 am" src="https://user-images.githubusercontent.com/19935974/28421044-fd62ac48-6d31-11e7-9749-153b7e92d304.png">

Error message will show in it's regular location. @floresj

**Comment by floresj** [comment]
Question about consistency... if we go the route of highlighting the header for errors, would we need to do it for all fields? For instance, here's an example with Weight and the hair color:

![selection_355](https://user-images.githubusercontent.com/5938731/28590791-6db62b78-7151-11e7-86fc-baaff4db4ae9.png)

Would the title for `Weight` also need the left border and error icon? Same thing for say a name:

![selection_356](https://user-images.githubusercontent.com/5938731/28590837-9dbbb1b2-7151-11e7-95fa-d65622b9b505.png)

We can discuss in hangout if that's easier. Just talking out loud now.

@Jay-Neighbours-I72 @bmallred

**Comment by bmallred** [comment]
Placing the CSS class `usa-input-error` on a parent element highlights all `input`, `select`, `textarea` elements appropriately.

So is the idea to have a completely new way of highlighting errors?

**Comment by Jay-Neighbours-I72** [comment]
I don't think we should highlight all headlines, only those without a single input.

Bryan - No, the idea is to have a different style for items with errors that don't have a single input for us to highlight with the red stroke, ex: Hair color

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this means we will have to go through and explicitly declare those because there is no way to reliable tell what does and doesn't match this use case.

**Comment by Jay-Neighbours-I72** [comment]
Got it, this was the original problem I was solving:
"Any ideas on what the required error state would look like for questions that use radio/checkbox options?"

Should that be changed? Does the style need to be applied to all inputs instead of just those specific ones mentioned up there^?

@bmallred @floresj

**Comment by Jay-Neighbours-I72** [comment]
@bmallred and I regrouped on this quickly and the solution is:

Use the existing error style and use the red border around all inputs associated to the question.

**Comment by billy22g** [comment]
The error styles themselves seem reasonable now. However, a couple things still not working quite right.

1. If I skip several required subsections, then fill them out in the review portion, they still don't seem to show up as "complete" on the navigation portion.

<img width="310" alt="screen shot 2017-08-24 at 11 04 40 am" src="https://user-images.githubusercontent.com/5091167/29678602-686ee678-88bc-11e7-818b-fd0d9403a288.png">

2. The required error message for phone numbers, or potentially any accordion type thing, is located inside the collapsed accordion. The user doesn't know about the error until they expand that accordion item.

<img width="896" alt="screen shot 2017-08-24 at 11 08 52 am" src="https://user-images.githubusercontent.com/5091167/29678656-a838fc08-88bc-11e7-996f-0421a64c01a9.png">

<img width="883" alt="screen shot 2017-08-24 at 11 09 20 am" src="https://user-images.githubusercontent.com/5091167/29678671-b3ea9c78-88bc-11e7-82c7-79b96183629d.png">

3. Filling out the SSN in the review screen still shows an error even after you've done it because you're not able to do the confirmation step on the review screen, but must navigate back to the SSN-specific subsection to be able to confirm it.

**Comment by floresj** [comment]
@billy22g I will check out those issues. For the second bullet point on accordions, we're tracking that in a separate user story located here https://github.com/truetandem/e-QIP-prototype/issues/1825. This is a task I'm working on now.

**Comment by billy22g** [comment]
LGTM
