### ISSUE TITLE
Add subsection title inside of sticky header

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#1600]
As a user, I want to see the subsection title within the main header when it is in a fixed state so that I can retain the context of which section I am editing in the form.

Acceptance Criteria
- [x] Add the subsection header in addition the section name to the form header.
- [x] As I scroll and the header locks into the top of the form, the sub section header remains visible with the header

**Comment by bmallred** [comment]
## Regular header

![image](https://user-images.githubusercontent.com/697855/28380963-2ed45b88-6c87-11e7-8605-b176cef8826e.png)

## Sticky header

![image](https://user-images.githubusercontent.com/697855/28380978-3a30386c-6c87-11e7-8bc9-9a3834735899.png)

**Comment by Jay-Neighbours-I72** [comment]
Man it does get really long.

I like the different sizes, maybe we cap it at the last 2 levels though?

Ex: Use of information technology systems > Unauthorized access

**Comment by colinpmacarthur** [comment]
I agree we should cap it at two levels.

**Comment by bmallred** [comment]
Revisions made from comments above...

## Two levels (normal)

![image](https://user-images.githubusercontent.com/697855/28530903-34af7468-7063-11e7-974d-61ad7c48726e.png)

## Two Levels (sticky)

![image](https://user-images.githubusercontent.com/697855/28530935-41536148-7063-11e7-8608-bae4ab170e2b.png)

## Three levels (normal)

![image](https://user-images.githubusercontent.com/697855/28530949-4f2d6048-7063-11e7-858c-9ffce8f57616.png)

## Three levels (sticky)

![image](https://user-images.githubusercontent.com/697855/28530970-5c35611e-7063-11e7-8060-b9e2a5aa15a4.png)

cc: @Jay-Neighbours-I72 @colinpmacarthur

**Comment by Jay-Neighbours-I72** [comment]
Looks good to me.

**Comment by colinpmacarthur** [comment]
This is also looking good to me, but I want to make sure @billy22g has a chance to see it, too. :smile:

**Comment by billy22g** [comment]
Hmmm...it feels a bit inconsistent, I almost feel like we should *always* have the top level section. But it's confusing when you're in the third level deep, because which two do you show? Thoughts @colinpmacarthur?

**Comment by colinpmacarthur** [comment]
My rule of thumb here: Prioritize telling people the things they're most likely to forget.

My guess about what folks are most likely to forget when they're three levels into the form, from most to least likely:
- The top level header
- The second level header
- The header related to the question they're answering now

So, if we continue to cap the breadcrumbs at two levels, I'd advocate putting the top and second level in there (rather than the second and third) as we're doing now.

Thoughts @billy22g or @Jay-Neighbours-I72 ?

**Comment by Jay-Neighbours-I72** [comment]
I think that order of what people are most likely to forget is correct.

However I think the most important one to have in the header is the one related to the question they are answering now. (the third level)

For example if they are in Foreign activities>Foreign activities>Indirect control
IMO "Indirect control" is the most important part to remember because it is directly related to their current actions. 

They may wonder if they are in the "Direct control" or "Indirect control" section. With that third level gone they lose that context.

Maybe a happy middle ground here would be to show only the first and last level? Maybe add some sort of indicator to show that the in between levels are being truncated/not shown?

**Comment by billy22g** [comment]
I think I agree with Jay that the last is most important for contextual purposes. I was thinking first and third as well, but that also feels weird. Agh.

**Comment by bmallred** [comment]
Would it be worth not using the actual title found in the navigation header and defining something else within the configuration file?

```
Use of information technology systems > Unauthorized access
```

can be something along the lines of

```
IT systems > Unauthorized access
```

**Comment by billy22g** [comment]
I'd prefer to stay consistent with naming I think, but again, this one seems tough.

**Comment by colinpmacarthur** [comment]
I agree with Billy -- I think using shortened names would probably add a layer of confusion.

@Jay-Neighbours-I72 and I discussed adding some visual styling to indicate that we're skipping a level, like:
Level 1 > ... > Level 3

**Comment by colinpmacarthur** [comment]
I'm going to move this back to "In progress" because I think @Jay-Neighbours-I72 is working on another mock.

**Comment by Jay-Neighbours-I72** [comment]
<img width="1526" alt="screen shot 2017-07-31 at 10 20 21 am" src="https://user-images.githubusercontent.com/19935974/28783740-47ce9462-75df-11e7-8275-e8f37cc83d3a.png">
<img width="1528" alt="screen shot 2017-07-31 at 10 20 27 am" src="https://user-images.githubusercontent.com/19935974/28783741-47d561e8-75df-11e7-8434-d20c6e1c6a39.png">

Or maybe an ellipsis:
<img width="1529" alt="screen shot 2017-07-31 at 10 20 58 am" src="https://user-images.githubusercontent.com/19935974/28783751-519003f0-75df-11e7-8891-93e49131a01e.png">


Thoughts?

**Comment by Jay-Neighbours-I72** [comment]
Revised idead:
Shift the visual weight to the last item.
<img width="1525" alt="screen shot 2017-07-31 at 3 23 37 pm" src="https://user-images.githubusercontent.com/19935974/28794405-3e34e5c6-7604-11e7-9ad5-136e1fd7e68e.png">

**Comment by Jay-Neighbours-I72** [comment]
Small size:
<img width="1940" alt="screen shot 2017-07-31 at 3 34 52 pm" src="https://user-images.githubusercontent.com/19935974/28794866-dad8b136-7605-11e7-98bb-b797bd8225fa.png">

**Comment by bmallred** [comment]
## Large

![image](https://user-images.githubusercontent.com/697855/28832456-77e20eba-76aa-11e7-96b2-8e0c411bdd62.png)

## Small

![image](https://user-images.githubusercontent.com/697855/28832467-84e77da2-76aa-11e7-9158-f20ca38e0a6e.png)

**Comment by billy22g** [comment]
Beautiful! LGTM

**Comment by billy22g** [comment]
Discussion during sprint review:

1. This is good.
2. Question from Nic around whether it's confusing to have it in the header, and whether it should be decoupled from the main header title.
