### ISSUE TITLE
Section 1 - Information About You - Visual

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1707]
Chrome-Win7
Header Bar appears to not utilizing space efficiently.

![image](https://user-images.githubusercontent.com/30842622/29128302-73536c70-7cf1-11e7-843d-8704d4da56eb.png)

**Comment by Jay-Neighbours-I72** [comment]
Header size is large by design to draw attention to the section anchors and it shrinks as user scrolls down.

Closing this one since this was the approved design, happy to re-open if it needs further discussion. 

<img width="1875" alt="screen shot 2017-09-29 at 1 31 21 pm" src="https://user-images.githubusercontent.com/19935974/31028067-9795b402-a51a-11e7-86c6-bbff532c6df3.png">
