### ISSUE TITLE
Write spec for "Foreign Business - Contacts"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1858]
Write the feature specification for the "Foreign Business" subsection "Contacts"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/29823513-e616b4aa-8c9c-11e7-9e64-40326fb770dd.gif)

**Comment by billy22g** [comment]
@pjsumm Same thing here as in #1843. Seems like the happy path would check something in that last question (no other contact to report).

**Comment by bmallred** [comment]
@billy22g good catch. Looks like it does have the value being set in code but it isn't set due to a bug

Spec: https://github.com/truetandem/e-QIP-prototype/commit/be38f42e8cd58a24e59ec4bb2567384da4c5d157#diff-c618fb1d586989a4720ee07dec9869ecR286
Bug: https://github.com/truetandem/e-QIP-prototype/issues/2279

**Comment by billy22g** [comment]
@pjsumm or @bmallred Would y'all mind loading another gif of this please?

**Comment by pjsumm** [comment]
I was able to work out the selector to grab the next instance of the question, so we can now select the "no" button.

![testresult](https://user-images.githubusercontent.com/12962390/34849724-6d221f0c-f6f1-11e7-9766-70d84d5496e8.gif)

**Comment by billy22g** [comment]
LGTM
