### ISSUE TITLE
Where you went to school - Person who knows you details

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1895]
Looks like we have a few extra blocks...

Remove:
- [ ] Provide date of last contact
- [ ] Relationship

Add:
- [ ] `I don't know` button to name

We can re-work the "person who knew you" branch

- [ ] Only show the "Name of person..." block at first
- [ ] If user selects "I don't know" for "Name of person.." the rest of this branch remains hidden
- [ ] If user fills in a name show the rest of the branch (Address, phone, email)

![screen shot 2017-09-07 at 4 15 29 pm](https://user-images.githubusercontent.com/19935974/30183258-c7125512-93e7-11e7-9fa2-7cca352470f5.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 for the **I don't know** should we not show any other reference information if this is selected? It seems odd if someone doesn't know the name to a reference that they would know any of the other information.

**Comment by Jay-Neighbours-I72** [comment]
I agree it is really strange and I'm not sure on hiding the rest of the info. My gut says we wouldn't hide it.

@porta-antiporta you have any thoughts? Maybe we bring it up to Sheldon/Drew?

**Comment by porta-antiporta** [comment]
(Note I edited the original comment for clarity; lmk if i misunderstood the entry)

Thinking along design patterns, I'm not a fan of hiding fields when "I don't know" is selected. 

It seems that `I don't know` is the mechanism the app uses to allow a *mandatory* field to be left intentionally blank.  But then defining another behavior pattern of what to hide (nested `I don't know` logic for the person's email etc) sounds like more work that should be avoided.

What I am wondering though is whether we can re-use an existing pattern in the app.
IIRC correctly, there's a `Yes/No` interaction that will render additional fields if `Yes` is selected.

Are we able to rephrase the questions along the lines of: `Is there someone who knows/knew you at that school?` followed by `Yes` or `No` buttons.

i.e. Rather than hiding fields when `I don't know` is selected; render fields when `Yes` is selected.

**Comment by Jay-Neighbours-I72** [comment]
I agree with your first point 100% @porta-antiporta , the way we currently handle the "I don't know" buttons is greying out the unused inputs when that button is selected. User can de select it and these inputs come back to full opacity, that way we are not showing/hiding. 

It is a little different what Bryan is suggesting though.

He means if a user answers "I don't know" for "Provide the name of the person..."
Would we hide the following fields related to this person: Address, Phone, Email. 
Correct me if I'm wrong @bmallred 

My thought on that was that we shouldn't hide any of the fields and keep true to the PDF form (even though it is a bit odd here). We should run it by Sheldon and Drew at some point, they may have some insight.


To your second point we have used an additional Yes/No question to load or hide a branch for users. This helped us simplify by only showing fields that the user "Needed" to fill out.

Unfortunately I don't think we can do that in this case because this branch is mandatory if the dates of attendance were within the last 3 years.

I'm happy to email Sheldon and Drew the question around this unless you would prefer to @porta-antiporta 

Let me know if that all makes sense.

**Comment by Jay-Neighbours-I72** [comment]
Per email Sheldon and Drew would like to hide the rest of this branch if the user answers "I don't know" to the name.

@bmallred I will update above.
