### ISSUE TITLE
Date Expire / No Error Shown

### ISSUE THREAD

**Issue by myukna72** [truetandem/e-QIP-prototype#1926]
Investigative and criminal history >Involvement in non-criminal court actions

The question is, "In the last ten (10) years, have you been a party to any public record civil court action not listed elsewhere on this form?"

The user can enter dates past 10 years without getting an error telling them that the incident is prior to the 10 year cut off date. 
<img width="775" alt="screen shot 2017-09-14 at 11 01 19 am" src="https://user-images.githubusercontent.com/30809116/30437251-22753cae-993c-11e7-9bec-1425a73725e0.png">

<img width="833" alt="screen shot 2017-09-14 at 11 01 35 am" src="https://user-images.githubusercontent.com/30809116/30437263-29179520-993c-11e7-81d8-7429a359c558.png">

**Comment by porta-antiporta** [comment]
My thoughts on what _should_happen:

# validation error fires upon submission
# Year field is flagged as red error
# Error dialogue box indicating something along the lines"only court actions within 10 years of today's date are needed"

@Jay-Neighbours-I72 is there a `warning` validation message style available (i.e. soft error, user can ignore and continue?). That could be another style we use if it already exists.  I wouldn't create a `warning` style just for this though.

**Comment by Jay-Neighbours-I72** [comment]
@porta-antiporta We don't have a soft error style, only the red error.

My thought is if an error is there we should flag it in red because it needs to fixed before form is submitted. I like the simplicity of one error message style, keep it simple for users. If some is red there is a problem and it needs to be fixed. Less for the user to learn. Would like @lauraponce input as well.


I do like adding this validation rule though, any time we can save a user from putting in unnecessary info it saves them time.

**Comment by Jay-Neighbours-I72** [comment]
Per standup:

Soft error is Sheldon & Drew's preference in situations like this.

Message something along the lines of "This isn't required but you are welcome to continue adding."

**Comment by porta-antiporta** [comment]
Gah, sorry about that.  My intent was to ask whether warnings already existed; not to create additional work.

IMHO, this falls under "not necessary for pilot".

**Comment by Jay-Neighbours-I72** [comment]
Closing this based on discussions around soft errors. If they are requested multiple times in usability tests we can revisit.

**Comment by billy22g** [comment]
Thanks Jay, good to go here.
