### ISSUE TITLE
Your History - School counters not working

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2312]
- [x] School and Degree counters are not working

![screen shot 2017-12-13 at 1 30 46 pm](https://user-images.githubusercontent.com/19935974/33955536-e3667fae-e009-11e7-8032-3ccd481cafea.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Not seeing this on dev:

- [ ] The school in this example is complete but still showing an error

![screen shot 2018-01-11 at 3 19 31 pm](https://user-images.githubusercontent.com/19935974/34845432-d5dd02aa-f6e2-11e7-9444-38649c5c957f.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 can you try again? Thinking you tested before `dev` was updated since it is a manually update process. I'm seeing it count appropriately right now.

**Comment by lauraponce** [comment]
@bmallred I just tried this on dev and it looks like the counter is still not counting

**Comment by bmallred** [comment]
Going to take a look at this now

**Comment by floresj** [comment]
Remember what we think @Jay-Neighbours-I72 .

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 @lauraponce 

![image](https://user-images.githubusercontent.com/697855/36216570-31d92de0-117d-11e8-9719-7048726b7ca3.png)

Currently the counters only account for items added within 10 years to 2 years (dependent on 18th birthday). This was derived from the epic #336 and subsequent issues #481 and #488.

@Jay-Neighbours-I72 did bring up a good question on how this may be confusing since

 1. first, we ask for **"Have you attended any schools in the last 10 years?"**
 2. if they answer "No", then we ask **"Have you received a degree or diploma more than 10 years ago?"**
 3. and finally, the last question asked in the section is **"Do you have additional education to enter (include education within the last 10 years, as well as degrees or diplomas more than 10 years ago)?"**

This seems to imply only the school counter has the 10 - 2 year limitations placed on it and the degree/diploma counter does not. Then, if this is in fact the case, it may be confusing to the applicant since some things are counted and others are not.

**Comment by Jay-Neighbours-I72** [comment]
My thoughts are that if an item is added to the accordion it should be reflected in the counters. To me that is expected behavior. 

Thoughts @lauraponce ?

**Comment by lauraponce** [comment]
I think I might be confused about this. For the expected behavior you are saying @Jay-Neighbours-I72, a user would potentially see the counter show that the schools go up to 3 for example, for schools just in the last 10 years, and that the degrees counter would go up to more than 3 if they have degrees from more than 10 years ago?

**Comment by Jay-Neighbours-I72** [comment]
@lauraponce  Expected for me would be:

school and degree from 2017 is added to accordion and shown in counter
school from 1988 and degree is added to accordion and shown in counter
school from 2002 and 2 degrees added and all shown in counter

So anything that is added to the accordion is reflected in the counters (regardless of in our out of the 10yr period for schools).

Currently schools that are older than 10yrs are not shown in counter which I think is confusing.

We can bring up in standup tomorrow is that is easier.

**Comment by bmallred** [comment]
From the conversion w/ @Sheldon1013 and @DBrenenborg we are going to go ahead with counting all captured schools and diplomas/degrees in the summary counters.

cc: @Jay-Neighbours-I72 @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
lgtm
