### ISSUE TITLE
People who know you well -> Number of people counter is strange

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#2353]
I've only entered 3 people, but it's showing 5/3 people, and the people shown are "Person 2", "Person 4", and "Person 5".

<img width="770" alt="screen shot 2017-12-27 at 1 19 33 pm" src="https://user-images.githubusercontent.com/5091167/34392328-c2f6f0be-eb08-11e7-9ebc-abc884841444.png">

<img width="803" alt="screen shot 2017-12-27 at 1 19 52 pm" src="https://user-images.githubusercontent.com/5091167/34392332-c7c17ccc-eb08-11e7-8422-c1b02a48349d.png">

**Comment by billy22g** [comment]
Still counting over the 3/3.


<img width="674" alt="screen shot 2018-01-16 at 4 05 56 pm" src="https://user-images.githubusercontent.com/5091167/35016740-2f626840-fad7-11e7-9385-25fe7d8b62ee.png">

**Comment by Jay-Neighbours-I72** [comment]
@billy22g Uh oh, I just commented the opposite of this direction in another issue:
https://github.com/truetandem/e-QIP-prototype/issues/2504

My opinion on this is similar to the Where you went to school counter. I'm a fan of counting everything that is put into the accordion. If we stop counting at 3 users may think there is an issue with the form itself. I'm ok with 4/3, 5/3 or any number over the 3 cap because it is accurately reflecting the accordion.

Maybe we talk through this one on a standup?

**Comment by billy22g** [comment]
Ah, got it Jay. Your reasoning makes perfect sense, though I’m not positive I agree. :) Let’s talk through it in the next few days. I may miss tomorrow’s standup but will be on planning and the rest of the week’s standups I think.
		
		

		
	




On Mon, Mar 5, 2018 at 12:56 PM -0700, "Jay Neighbours" <notifications@github.com> wrote:












@billy22g Uh oh, I just commented the opposite of this direction in another issue:

#2504


My opinion on this is similar to the Where you went to school counter. I'm a fan of counting everything that is put into the accordion. If we stop counting at 3 users may think there is an issue with the form itself. I'm ok with 4/3, 5/3 or any number over the 3 cap because it is accurately reflecting the accordion.


Maybe we talk through this one on a standup?

**Comment by Jay-Neighbours-I72** [comment]
lgtm
