### ISSUE TITLE
Help icon - breaking on new line

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2527]
Is there a way to prevent the help icons from breaking onto their own line?

![screen shot 2018-01-29 at 9 46 16 am](https://user-images.githubusercontent.com/19935974/35516284-60f38676-04d9-11e8-978b-17a7c860513a.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 for cases like this one unfortunately no. Both the title text and the help icon are `inline` meaning the follow natural textual flow. The reason this instance goes to the next line is because the accordion sets a width value and the text is taking up too much space to also fit the help icon on the same line.

We welcome any ideas to work around this of course!

**Comment by Jay-Neighbours-I72** [comment]
got it
