### ISSUE TITLE
Foreign business - Event participation - contact yes/no

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2541]
- [ ] Changed the yes to a no, clicked yes on the confirm message, No was still de-selected

Also happening on immediate family contact and looks like it is only the second yes/no in the contact branch

![screen shot 2018-01-30 at 10 44 25 am](https://user-images.githubusercontent.com/19935974/35575591-c30a7cda-05aa-11e8-9903-ef2de52634fb.jpg)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 I think this is similar to one of the longstanding issues on how the branch collections should behave. For instance, if you select `Yes` to the first two branch questions, you get the following:

![selection_706](https://user-images.githubusercontent.com/5938731/36031168-d5a04e68-0d77-11e8-834d-370588d55627.png)

Notice how the last branch collection branch is empty. That's because the user still has to confirm if they have another one. Now, if you delete any of the first two selected branch collections, you get this:

![selection_707](https://user-images.githubusercontent.com/5938731/36031240-166392ac-0d78-11e8-92a8-422e44518d24.png)

This is intentional because we would be assuming the user is done. The user still needs to confirm if they have any additional entries.

Now, if there's only *one* item selected and they click no, then we leave the last branch item marked as `No`
![selection_709](https://user-images.githubusercontent.com/5938731/36031312-4aca0fee-0d78-11e8-8eab-9086d7b892c0.png)

cc: @bmallred

**Comment by bmallred** [comment]
@floresj you are correct.

## Start with the following
![image](https://user-images.githubusercontent.com/697855/36166169-b4863800-10bf-11e8-862c-e78d1463b667.png)

## Removing the third item
![removing-third-item](https://user-images.githubusercontent.com/697855/36166715-6507657c-10c1-11e8-99f3-18455c361671.gif)

## Removing the second item
![removing-second-item](https://user-images.githubusercontent.com/697855/36166707-60ce82f6-10c1-11e8-9f09-bc488783ab25.gif)

## Removing the first item
![removing-first-item](https://user-images.githubusercontent.com/697855/36166702-5d22179e-10c1-11e8-8cb9-1779cd2a94b2.gif)

cc: @Jay-Neighbours-I72

**Comment by floresj** [comment]
@bmallred +1 for the gif. :taco:
