### ISSUE TITLE
Configuration guide updates

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2633]
Improve and expand configuration information and examples in the eApp README to to be more comprehensive.

**Comment by ryanhofdotgov** [comment]
Here are some specific suggestions for the README as well as the sample .env* files at the root of the project:

* Platform build scripts have been tested with – e.g., docker version requirements or operating system.  FYI, I did my testing under stock RHEL7 as that is not an atypical OS for a defense contractor, macOS is probably not that common. SELinux (which is enabled by default in RHEL7) breaks the docker-compose scripts (config files in the project dir in host environment that were mounted in the container couldn't be read by the container). After disabling SELinux, it worked. 

* Explicit list of all base dependencies. For example on RHEL7 minimal install, I had to do:
`yum install golang docker-latest git`
`# Add EPEL yum repository`
`yum install python2-pip`
`pip install docker-compose`
`yum install glide nodejs`
`# Add yarn yum repository`
`yum install yarn`

* Briefly mention that the scripts will deploy N primary containers, `web`, `api`, `database`, etc., derived from base images on `hub.docker.com` and then point to your architectural diagram. And that the IdAM is not part of this project.

* Reference the appropriate `make` commands instead of the `docker-compose` or `yarn` commands. I think if you do this, then the cert generation issue I hit becomes moot.

* Update the localhost .env example and reference it explicitly in the quick start steps. Here is what I ended up using:
```NODE_ENV=development
GOLANG_ENV=development
LOG_LEVEL=
API_BASE_URL=
USPS_API_API_KEY=
HASH_ROUTING=
CORS_ALLOWED=*
ALLOW_2FA_RESET=
BASIC_ENABLED=1
DISABLE_2FA=1
FLUSH_STORAGE=
SAML_ENABLED=
SAML_PUBLIC_CERT=
SAML_PRIVATE_CERT=
SAML_IDP_SSO_URL=
SAML_IDP_SSO_DESC_URL=
SAML_IDP_PUBLIC_CERT=
SAML_SIGN_REQUEST=
SAML_CONSUMER_SERVICE_URL=
TLS_CERT=
TLS_KEY=
WS_URL=
WS_KEY=
```
