### ISSUE TITLE
Pilot feedback survey

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2840]
As an eApp pilot applicant after completing the eApp form  I want have an opportunity to provide feedback so that I can help improve the overall experience.

Acceptance Criteria

- [x]  Create survey for applicants
- [x]  Decide where and when to give the applicant the survey
- [x]  Approve survey/plan with the 18F team & product owner

**Comment by Jay-Neighbours-I72** [comment]
Recommend using a google survey from an 18F account (probably Ben) for officialness and 18F owned results location.

Goal with these 3 questions is to be light and open ended to give applicants a chance to be as brief or verbose as they want.

Ideas for survey questions:
1. What did you like and/or dislike about your experience
2. If you could change one thing about the form what would it be
3. Any other thoughts or feedback

**Would you like to provide more feedback?**
If you are interested in a short call to share more feedback and help improve the overall experience contact xxx@email.com.


Thoughts on where and when to give the survey

1.  On final screen after submission
Pros: Immediate feedback when experience is fresh in their mind
Cons: Applicant may be exhausted from filling out the form and doesn't want to do a survey

2. In a follow up email
Pros: Applicant may be over form fatigue by this point
Cons: More time passed between filling out form and survey = less fresh in mind. May ignore or miss email.

I'm leaning more towards wrapping it in with the final submission screen and see how many results we get. If that number is really low then switch to email.


Thoughts @bpdesigns @ryanhofdotgov Michael (what is your GH name?)

**Comment by bpdesigns** [comment]
@Jay-Neighbours-I72 I like the idea adding to the end of the form and changing to email if needed. 

I think the survey questions are solid but had a thought. For question 1. "What did you like and/or dislike about your experience" I wonder if people will choose to give either their "like" or "dislike" instead of both?

What if it was something like:
1. What did you like about your experience with the form?
2. What could be made better?
3. What would you change/ or other feedback?

Also, will people know they are participating in a pilot? I wonder if we should include a title like "Help make e-qip better" or a sentence on the page above survey questions thanking them for participating in the pilot?

**Comment by Jay-Neighbours-I72** [comment]
Good points!

I believe they will know they are part of the pilot so that is a great point about the headline on the survey.

**Comment by Jay-Neighbours-I72** [comment]
Working form: 
https://docs.google.com/forms/d/e/1FAIpQLSfhh9DzMhJfZLoAJ8TYKd9dFGnc2wGI4dpwD6wRMkAZf2SIlA/viewform

**Comment by bpdesigns** [comment]
Thoughts on making the form one page?

also for 3. do you think it should just be "Do you have other feedback?"

**Comment by bpdesigns** [comment]
I really like it on one page. 

What do you think about asking them to leave an email address for us to follow up instead of telling them to contact an email?

ie.

Would you like to provide more feedback?
If you are interested in a short call to share more feedback and help improve the overall experience please leave youre email so we can follow up and schedule a call - or something like this?

**Comment by Jay-Neighbours-I72** [comment]
That is a great idea! Less work for them.

Updated it, take a look. I shortened the last question a bit and removed the "improve overall experience.." because we say that in the intro. Thoughts?

**Comment by bpdesigns** [comment]
great

**Comment by bpdesigns** [comment]
@Jay-Neighbours-I72 I've recreated the form in my account and tweaked some of the copy for the last question and the email request. 

Please preview here: https://goo.gl/forms/sCkSDIxWLvTwqTWo2

**Comment by Jay-Neighbours-I72** [comment]
Nice! That last question rework is great! Much easier to read

**Comment by Jay-Neighbours-I72** [comment]
Plan:

- Survey link will live on the last page of the form after submitting (the print page). If we don't get a lot of responses we can send follow up emails
- Survey link: https://goo.gl/forms/sCkSDIxWLvTwqTWo2

**Comment by Jay-Neighbours-I72** [comment]
Note: need to use the full link - shortened link is blocked by DOD
