### ISSUE TITLE
Emotional health - Competence - second question text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#832]
- [x] Main second question should be an H3

Prototype:
<img width="1001" alt="screen shot 2017-04-04 at 4 09 55 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676556/6b53976a-1951-11e7-85b2-cb46df4cc0a0.png">

-

Comp:
<img width="904" alt="screen shot 2017-04-04 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676561/71a079b2-1951-11e7-9140-e01ec3421a06.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @bmallred @joeignition 
Ok, general question about the accordion text that's at the bottom. Jay you mentioned here that the second question text should be an h3. So that right now is defined as an h2 in our Accordion component so everything is getting an h2. Should we just make that an h3 site wide then?

**Comment by Jay-Neighbours-I72** [comment]
Yeah @floresj  they should always be H3 as defined in the comps and the wireframe docs.

Are they technically part of the accordion? I assumed they were not because they sit below it rather than inside it.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 they are part of the accordion because of the tie in to creating a new item.

**Comment by Jay-Neighbours-I72** [comment]
Ahhhhhhh @bmallred I get it! That makes sense.
